phpdef-fpm-goha:
    build: .
    environment:
        - TZ=Asia/Jerusalem
    ports:
        - 9003:9000
    volumes:
        - /etc/timezone:/etc/timezone:ro
        - /usr/local/src/site:/usr/local/src/site
        - /usr/local/src/app:/usr/local/src/app
        - /usr/local/src/themes:/usr/local/src/themes
        - /srv/nfs/share/vol2/www/imageshare/sites/brands:/srv/nfs/share/vol2/www/imageshare/sites/brands
        - /srv/www/htdocs:/srv/www/htdocs
